// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200602222727");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.update.auto.migrated", true);
user_pref("app.update.backgroundErrors", 3);
user_pref("app.update.disable_button.showUpdateHistory", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1604483258);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1604482966);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1604482939);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1604483229);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1604483086);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1604482996);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.capacity", 921600);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1604482936);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{10088d5a-22e0-43ae-808b-5acdcec3fb00}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200602222727");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 4309);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1604483228);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1604482938247");
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200602222727");
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"551d42ef-eb40-4ef6-90b5-0709bbf7660a\",\"formautofill@mozilla.org\":\"2a11c95a-53fb-4075-b18f-6b2ac72a4b70\",\"screenshots@mozilla.org\":\"56b4fb82-d1c3-42fd-a124-f3a66f23ed2d\",\"webcompat-reporter@mozilla.org\":\"ee8f0b0c-4084-45bf-ba39-2889d04ab5f3\",\"webcompat@mozilla.org\":\"40f4d871-6e5c-4010-89f9-5e22e8a9b5ef\",\"default-theme@mozilla.org\":\"798a8364-3d20-4966-b663-19abb9d9901e\",\"google@search.mozilla.org\":\"2a2627dc-37bc-47eb-9347-17413eda12cf\",\"bing@search.mozilla.org\":\"24813632-e4d5-4cee-8335-9fada9249596\",\"amazon@search.mozilla.org\":\"bc335ca5-1ff8-4c88-9c09-8af49f562c2a\",\"ddg@search.mozilla.org\":\"55313df1-a5b0-4612-9703-02a01c7620d8\",\"ebay@search.mozilla.org\":\"b666e2d6-680e-4a85-88ec-418431452fcf\",\"qwant@search.mozilla.org\":\"6ea037c4-2401-4133-94d9-ea39e2a1802f\",\"wikipedia@search.mozilla.org\":\"2ef64a94-09a8-443f-962d-cd28fcf684d1\"}");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x00b8");
user_pref("sanity-test.driver-version", "10.0.19041.1");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20200602222727");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.pki.mitm_canary_issuer", "CN=CA-amon.etb1.lan,OU=ac-test,OU=110 043 015,O=Ministere Education Nationale (MENESR),C=FR");
user_pref("security.sandbox.content.tempDirSuffix", "{8b534208-aa69-4c6e-8b68-db3826070319}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{89e14c99-1d96-495a-8a02-0643702918cd}");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1604483222);
user_pref("toolkit.telemetry.cachedClientID", "57d4e3d0-adcc-4119-ae1d-09d7b37bd200");
user_pref("toolkit.telemetry.previousBuildID", "20200602222727");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
