#!/usr/bin/python

from __future__ import print_function

import sys
import traceback

from creole.loader import creole_loader
from creole.loader import config_save_values

try:
    print("Load EOLE configuration... ", end='')
    loader = creole_loader(load_extra=True)
    print("OK")
except Exception, error:
    print(error)
    traceback.print_exc()
    sys.exit(1)

try:
    print("Save EOLE configuration... ", end='')
    config_save_values(loader, namespace='creole', reload_config=False)
    print("OK")
except Exception, error:
    print(error)
    traceback.print_exc()
    sys.exit(1)
