#!/bin/bash
(
if [ -z "$2" ]
then
    echo "T=$7 $1 U=$2 u=$8 a=$3 m=$4 I=$5 M=$9 d=$6 R=${10} H=${11} : Démarrage" 
else
    if [[ "$2" == *_ ]]
    then
       echo "T=$7 $1 U=$2 u=$8 a=$3 m=$4 I=$5 M=$9 d=$6 R=${10} H=${11} : Compte machine '_' !" 
    else
        if [[ "$2" == *\$ ]]
        then
            echo "T=$7 $1 U=$2 u=$8 a=$3 m=$4 I=$5 M=$9 d=$6 R=${10} H=${11} : Compte machine '\$' !" 
        else
            echo "T=$7 $1 U=$2 u=$8 a=$3 m=$4 I=$5 M=$9 d=$6 R=${10} H=${11} : Compte utilisateur !"
        fi
    fi
fi
) 2>&1 | tee -a /tmp/dyn-logon | tee /dev/tty1
exit 0
